-- Diagnóstico de estructura de tablas
-- Ejecutar contra la BD MineDax para verificar estructura real

-- 1. Verificar si existen las tablas esperadas
SELECT
  TABLE_NAME,
  CASE
    WHEN TABLE_NAME = 'NO_NOVED' THEN 'Novedades (Permisos/Licencias)'
    WHEN TABLE_NAME = 'NO_AUSEN' THEN 'Ausencias (Vacaciones)'
    WHEN TABLE_NAME = 'NO_PERIOD' THEN 'Períodos'
    ELSE 'Otra'
  END AS Descripcion
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME IN ('NO_NOVED', 'NO_AUSEN', 'NO_PERIOD', 'GN_FUNCI', 'GN_TERCE')
ORDER BY TABLE_NAME;

-- 2. Estructura de NO_NOVED (Novedades/Permisos)
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'NO_NOVED')
BEGIN
  PRINT '==== ESTRUCTURA DE NO_NOVED ====';
  SELECT
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    ORDINAL_POSITION
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'NO_NOVED'
  ORDER BY ORDINAL_POSITION;
END
ELSE
BEGIN
  PRINT 'TABLA NO_NOVED NO EXISTE';
END;

-- 3. Estructura de NO_AUSEN (Ausencias/Vacaciones)
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'NO_AUSEN')
BEGIN
  PRINT '==== ESTRUCTURA DE NO_AUSEN ====';
  SELECT
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    ORDINAL_POSITION
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'NO_AUSEN'
  ORDER BY ORDINAL_POSITION;
END
ELSE
BEGIN
  PRINT 'TABLA NO_AUSEN NO EXISTE';
END;

-- 4. Estructura de NO_PERIOD (Períodos)
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'NO_PERIOD')
BEGIN
  PRINT '==== ESTRUCTURA DE NO_PERIOD ====';
  SELECT
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    ORDINAL_POSITION
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'NO_PERIOD'
  ORDER BY ORDINAL_POSITION;
END
ELSE
BEGIN
  PRINT 'TABLA NO_PERIOD NO EXISTE';
END;

-- 5. Ejemplos de registros existentes (si los hay)
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'NO_NOVED')
BEGIN
  PRINT '==== EJEMPLOS DE REGISTROS EN NO_NOVED ====';
  SELECT TOP 3 * FROM NO_NOVED;
END;

IF EXISTS (SELECT * FROM sys.tables WHERE name = 'NO_AUSEN')
BEGIN
  PRINT '==== EJEMPLOS DE REGISTROS EN NO_AUSEN ====';
  SELECT TOP 3 * FROM NO_AUSEN;
END;
