-- ================================================================
-- DIAGNÓSTICO COMPLETO - MineDax PDF Import
-- Ejecutar contra BD MineDax para verificar estructura real
-- Fecha: 2026-04-23
-- ================================================================

PRINT '╔════════════════════════════════════════════════════════════════╗'
PRINT '║         DIAGNÓSTICO DE ESTRUCTURA - MineDax                   ║'
PRINT '╚════════════════════════════════════════════════════════════════╝'
PRINT ''

-- ================================================================
-- 1. VERIFICAR EXISTENCIA DE TABLAS PRINCIPALES
-- ================================================================
PRINT '════ 1. VERIFICAR TABLAS PRINCIPALES ════'
SELECT
  TABLE_NAME,
  CASE
    WHEN TABLE_NAME = 'NO_NOVED' THEN 'Novedades/Permisos'
    WHEN TABLE_NAME = 'NO_AUSEN' THEN 'Ausencias/Vacaciones'
    WHEN TABLE_NAME = 'NO_CONCE' THEN 'Conceptos de Nómina'
    WHEN TABLE_NAME = 'NO_PERIOD' THEN 'Períodos de Nómina'
    WHEN TABLE_NAME = 'GN_FUNCI' THEN 'Empleados'
    WHEN TABLE_NAME = 'GN_TERCE' THEN 'Terceros (Personas)'
    ELSE 'Otra'
  END AS Descripcion
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME IN ('NO_NOVED', 'NO_AUSEN', 'NO_CONCE', 'NO_PERIOD', 'GN_FUNCI', 'GN_TERCE')
ORDER BY TABLE_NAME;

PRINT ''
PRINT '════ 2. ESTRUCTURA DE NO_NOVED (Permisos) ════'
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'NO_NOVED')
BEGIN
  SELECT
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'NO_NOVED'
  ORDER BY ORDINAL_POSITION;
END
ELSE
BEGIN
  PRINT 'ERROR: Tabla NO_NOVED NO EXISTE'
END;

PRINT ''
PRINT '════ 3. ESTRUCTURA DE NO_AUSEN (Vacaciones) ════'
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'NO_AUSEN')
BEGIN
  SELECT
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'NO_AUSEN'
  ORDER BY ORDINAL_POSITION;
END
ELSE
BEGIN
  PRINT 'ERROR: Tabla NO_AUSEN NO EXISTE'
END;

PRINT ''
PRINT '════ 4. ESTRUCTURA DE NO_CONCE (Conceptos) ════'
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'NO_CONCE')
BEGIN
  SELECT TOP 10
    COD_CONC,
    NOM_CONC,
    TIP_CONC,
    IND_ACT,
    ACT_ESTA
  FROM NO_CONCE
  WHERE NOM_CONC LIKE '%PERMISO%'
     OR NOM_CONC LIKE '%VACACIO%'
  ORDER BY NOM_CONC;
END
ELSE
BEGIN
  PRINT 'ERROR: Tabla NO_CONCE NO EXISTE'
END;

PRINT ''
PRINT '════ 5. PERÍODO ACTUAL ACTIVO ════'
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'NO_PERIOD')
BEGIN
  SELECT TOP 1
    COD_PERIOD,
    PER_ANO,
    PER_MES,
    PER_QNA,
    PER_FINI,
    PER_FFIN,
    PER_EST,
    ACT_ESTA
  FROM NO_PERIOD
  WHERE PER_EST = 'A'
    AND ACT_ESTA = 'A'
    AND CONVERT(date, GETDATE()) BETWEEN PER_FINI AND PER_FFIN
  ORDER BY PER_FINI DESC;
END
ELSE
BEGIN
  PRINT 'ERROR: Tabla NO_PERIOD NO EXISTE'
END;

PRINT ''
PRINT '════ 6. EMPLEADOS REGISTRADOS (Muestra) ════'
SELECT TOP 10
  f.COD_FUNCI,
  t.NUM_IDEN AS CEDULA,
  t.NOM_COMP AS NOMBRE,
  f.ACT_ESTA,
  t.ACT_ESTA AS ESTADO_TERCERO
FROM GN_FUNCI f
INNER JOIN GN_TERCE t ON t.COD_TERC = f.COD_TERC
WHERE f.ACT_ESTA = 'A'
  AND t.ACT_ESTA = 'A'
ORDER BY t.NOM_COMP;

PRINT ''
PRINT '════ 7. BÚSQUEDA ESPECÍFICA: Laura Velasquez (1858228240) ════'
SELECT TOP 1
  t.COD_TERC,
  t.NUM_IDEN AS CEDULA,
  t.NOM_COMP AS NOMBRE,
  t.ACT_ESTA,
  f.COD_FUNCI,
  f.ACT_ESTA AS ESTADO_EMPLEADO
FROM GN_TERCE t
LEFT JOIN GN_FUNCI f ON f.COD_TERC = t.COD_TERC AND f.ACT_ESTA = 'A'
WHERE t.NUM_IDEN IN (1858228240, 185822824)
ORDER BY t.NOM_COMP;

PRINT ''
PRINT '════ 8. ÚLTIMAS NOVEDADES INSERTADAS (Permisos) ════'
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'NO_NOVED')
BEGIN
  SELECT TOP 5
    COD_NOVED,
    COD_FUNCI,
    COD_CONC,
    FEC_INI,
    FEC_FIN,
    OBS_NOVED,
    ACT_USUA,
    ACT_HORA,
    ACT_ESTA
  FROM NO_NOVED
  WHERE ACT_USUA = 'SISTEMA'
  ORDER BY ACT_HORA DESC;
END
ELSE
BEGIN
  PRINT 'ERROR: Tabla NO_NOVED NO EXISTE'
END;

PRINT ''
PRINT '════ 9. ÚLTIMAS AUSENCIAS INSERTADAS (Vacaciones) ════'
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'NO_AUSEN')
BEGIN
  SELECT TOP 5
    COD_NOVED,
    FEC_INI,
    FEC_FIN,
    DIAS_TOTAL,
    DIAGNOSTICO,
    ACT_USUA,
    ACT_HORA,
    ACT_ESTA
  FROM NO_AUSEN
  WHERE ACT_USUA = 'SISTEMA'
  ORDER BY ACT_HORA DESC;
END
ELSE
BEGIN
  PRINT 'ERROR: Tabla NO_AUSEN NO EXISTE'
END;

PRINT ''
PRINT '════ 10. VERIFICACIÓN DE INTEGRIDAD ════'
DECLARE @TablaOk INT = 0
DECLARE @Mensaje NVARCHAR(MAX) = ''

-- Verificar NO_NOVED
IF EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'NO_NOVED' AND COLUMN_NAME = 'COD_NOVED'
)
BEGIN
  SET @Mensaje = @Mensaje + 'NO_NOVED: ✓ Estructura correcta' + CHAR(13) + CHAR(10)
  SET @TablaOk = @TablaOk + 1
END
ELSE
BEGIN
  SET @Mensaje = @Mensaje + 'NO_NOVED: ✗ Estructura incompleta' + CHAR(13) + CHAR(10)
END

-- Verificar NO_AUSEN
IF EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'NO_AUSEN' AND COLUMN_NAME = 'COD_NOVED'
)
BEGIN
  SET @Mensaje = @Mensaje + 'NO_AUSEN: ✓ Estructura correcta' + CHAR(13) + CHAR(10)
  SET @TablaOk = @TablaOk + 1
END
ELSE
BEGIN
  SET @Mensaje = @Mensaje + 'NO_AUSEN: ✗ Estructura incompleta' + CHAR(13) + CHAR(10)
END

PRINT @Mensaje
PRINT 'Tablas OK: ' + CAST(@TablaOk AS VARCHAR(2)) + '/2'

PRINT ''
PRINT '════════════════════════════════════════════════════════════════'
PRINT 'FIN DEL DIAGNÓSTICO'
PRINT '════════════════════════════════════════════════════════════════'
