-- ==========================================================================
-- ACTUALIZACIÓN COD_ESTCIV · GN_FUNCI · MineDax
-- Fuente de referencia: FORMATO NOVEDADES CM 2Q ABRIL 2026.xlsx
-- Pestaña: Maestro Original  ·  Generado: 2026-05-04
-- --------------------------------------------------------------------------
-- Total registros a actualizar : 152
-- Ya correctos (sin cambio)    : 19
-- --------------------------------------------------------------------------
-- Mapeo usado:
--   SOLTERO      → COD_ESTCIV = 1
--   CASADO       → COD_ESTCIV = 2
--   UNION LIBRE  → COD_ESTCIV = 3
--   DESCONOCIDO  → COD_ESTCIV = 0  (Sin asignar)
-- ==========================================================================

USE MineDax;
GO

-- ── VERIFICACIÓN PREVIA ────────────────────────────────────────────────────
-- Ejecuta esta consulta ANTES para ver el estado actual:
/*
SELECT
    ISNULL(ec.NOM_ESTCIV, '** NULL **') AS ESTADO_CIVIL,
    f.COD_ESTCIV,
    COUNT(*) AS TOTAL
FROM GN_FUNCI f
LEFT JOIN MAE_ESTCIV ec ON ec.COD_ESTCIV = f.COD_ESTCIV
GROUP BY f.COD_ESTCIV, ec.NOM_ESTCIV
ORDER BY f.COD_ESTCIV;
*/

-- ── INICIO TRANSACCIÓN ─────────────────────────────────────────────────────
BEGIN TRANSACTION;

BEGIN TRY

    -- ┌─ SIN ASIGNAR (COD_ESTCIV = 0) · 15 registros ─────────
    UPDATE GN_FUNCI SET COD_ESTCIV = 0, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 96;  -- 24339233  LONDONO OCAMPO VIVIANA
    UPDATE GN_FUNCI SET COD_ESTCIV = 0, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 98;  -- 25215588  IGLESIAS ESCUDERO KELLY JOHANA
    UPDATE GN_FUNCI SET COD_ESTCIV = 0, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 103;  -- 39178636  GARCIA SANCHEZ MICHELLY
    UPDATE GN_FUNCI SET COD_ESTCIV = 0, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 104;  -- 56098617  CORZO CONTRERAS MARIA ANGELICA
    UPDATE GN_FUNCI SET COD_ESTCIV = 0, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 117;  -- 75103216  OSPINA HINCAPIE HECTOR DAVID
    UPDATE GN_FUNCI SET COD_ESTCIV = 0, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 118;  -- 75103472  CANAS FRANCO DIEGO EDISON
    UPDATE GN_FUNCI SET COD_ESTCIV = 0, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 126;  -- 80083229  GUZMAN MONTANEZ JORGE ELIECER
    UPDATE GN_FUNCI SET COD_ESTCIV = 0, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 42;  -- 1059713194  DIAZ REYES ANDERSON DAVID
    UPDATE GN_FUNCI SET COD_ESTCIV = 0, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 43;  -- 1059713241  TAPASCO CHAURRA DAVINSON
    UPDATE GN_FUNCI SET COD_ESTCIV = 0, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 44;  -- 1059810513  GARCIA GALVIS OSCAR ALEJANDRO
    UPDATE GN_FUNCI SET COD_ESTCIV = 0, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 66;  -- 1067908034  PATERNINA POLO JESSICA
    UPDATE GN_FUNCI SET COD_ESTCIV = 0, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 70;  -- 1098680474  MENDOZA AFANADOR GERSON
    UPDATE GN_FUNCI SET COD_ESTCIV = 0, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 71;  -- 1098683398  RIVEROS RUEDA ORLANDO
    UPDATE GN_FUNCI SET COD_ESTCIV = 0, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 143;  -- 1002969887  GOMEZ GRISALES JUAN SEBASTIAN
    UPDATE GN_FUNCI SET COD_ESTCIV = 0, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 4;  -- 1027885783  RENDON HOYOS VICTOR ALEJANDRO

    -- ┌─ SOLTERO/A (COD_ESTCIV = 1) · 109 registros ─────────
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 105;  -- 5916737  CARDENAS MARTIN ROBINSON LEONARDO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 128;  -- 8239369  CARDOSO MARACAJA RAPHAEL CAPELLA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 88;  -- 15928324  ALVAREZ RINCON GERARDO ANTONIO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 90;  -- 15931551  RAMIREZ RAMIREZ DIDIER DE JESUS
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 91;  -- 15932818  GUEVARA  JOSE DAVID
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 94;  -- 16070773  OROZCO SALGADO JULIAN
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 97;  -- 24743274  GALLEGO MEJIA BEATRIZ HELENA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 100;  -- 33994016  VALENCIA VALENCIA LUZ MARY
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 101;  -- 33994809  RANGEL CONDE OLGA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 108;  -- 71315693  BENITEZ CORREA JUAN DIEGO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 109;  -- 74188499  PALACIOS ALVARADO CESAR AUGUSTO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 119;  -- 75107139  GIRALDO MORALES JONATHAN
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 120;  -- 75144193  TANGARIFE GONZALEZ JORGE HUGO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 121;  -- 79627976  SANTOS NIETO CARLOS ANDRES
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 129;  -- 86086222  CARMONA QUIROZ MARIO FERNANDO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 130;  -- 91531957  RODRGUEZ ROJAS JOSE ANTONIO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 132;  -- 1001014188  TILANO MONTOYA LAURA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 41;  -- 1059710108  GAÑAN BUENO JOSE ALBEIRO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 45;  -- 1059811303  CIFUENTES ARIAS JUAN ESTEBAN
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 46;  -- 1060267953  BERMUDEZ SERNA JULIAN DAVID
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 156;  -- 1060587212  ZAPATA CASTAÑO VANNESA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 157;  -- 1060587214  ALARCON ZAMORA YILMER ANDRES
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 158;  -- 1060587723  TORO AMARILES SANTIAGO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 48;  -- 1060588957  ARROYAVE MONTOYA ELIZABETH
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 49;  -- 1060589612  VINASCO LOAIZA JOSE TIBERIO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 53;  -- 1060594098  GALEANO AYALA GLORIA EDITH
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 55;  -- 1060594638  PIEDRAHITA CARTAGENA DANIEL ARMANDO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 56;  -- 1060594799  RIOS MARIN JUAN FELIPE
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 57;  -- 1060596363  LEON GIRALDO FELIPE
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 58;  -- 1060596650  ALARCON TEJADA JUAN PABLO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 59;  -- 1060596935  SERNA VILLADA VALENTINA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 60;  -- 1060596951  RODRIGUEZ RODRIGUEZ ANLLY PAOLA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 62;  -- 1060597775  FRANCO LLANES JUAN DIEGO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 63;  -- 1060598066  GUZMAN MEJIA ANA MARIA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 64;  -- 1060653592  LONDOÑO VANEGAS DAVID
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 65;  -- 1065004568  PACHECO GALEANO MOISES ALBERTO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 67;  -- 1071351401  SANCHEZ MASEA YOMAR JAVIER
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 68;  -- 1095510911  GUAZA VELASCO YOINER JAVIER
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 69;  -- 1098668023  PINILLA REYES OSCAR JAVIER
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 72;  -- 1098688603  OTERO CASTILLO IVON JOHANA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 73;  -- 1100950267  PEDROZA URIBE LAURA MARCELA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 79;  -- 1128422824  MARIN ESTRADA YURANY
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 160;  -- 1128455815  AREIZA PEÑA ANDRES
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 161;  -- 1143826339  GRANADA GIRON ARTURO ALEXIS
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 81;  -- 1152193844  DAVID VALLE SANTIAGO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 82;  -- 1192799435  VILLAMIL SEDANO SANTIAGO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 83;  -- 1192904166  OSORIO DIAZ JASON STEVENS
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 84;  -- 1193029566  MONSALVE ESTRADA JUAN SEBASTIAN
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 133;  -- 1001603682  OCAMPO PALACO SERGIO ANDRES
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 164;  -- 1002545489  GARCIA AYALA JUAN ESTEBAN
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 134;  -- 1002591008  LONDOÑO GIL SIMON
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 135;  -- 1002754987  RAMIREZ SANCHEZ JIMENA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 165;  -- 1002755126  MARIN GARCIA YENY ALEXANDRA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 136;  -- 1002814576  MORENO LARGO JHAN CARLOS
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 137;  -- 1002900089  MORENO QUINCHIA SEBASTIAN
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 138;  -- 1002900275  VELARDE MARULANDA YULIANA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 139;  -- 1002900482  HIGINIO CRUZ DANNA GERALDINE
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 166;  -- 1002900611  LEON QUICENO VALENTINA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 140;  -- 1002900779  RODRIGUEZ FLOREZ JUAN FELIPE
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 167;  -- 1002900824  ZAPATA CASTAÑO JENNY NATHALIA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 141;  -- 1002901033  VALENCIA RAMIREZ NIXON HERNEY
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 142;  -- 1002901077  FLOREZ AGUDELO MARIA DANIELA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 144;  -- 1005088926  BEDOYA SUAREZ JOSE DARIO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 145;  -- 1005089085  DIAZ ACEVEDO HAROLD IGNACIO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 146;  -- 1005098717  GAÑAN BUENO SAMUEL HUMBERTO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 147;  -- 1007224481  BOTERO NEQUIRUCAMA YEISON ESTIVEN
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 148;  -- 1007227275  JIMENEZ BENAVIDES MARIANA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 149;  -- 1007441856  BUENO GANON LUIS MANUEL
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 150;  -- 1007593984  TRILLERAS SANCHEZ JULIAN ALEXIS
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 151;  -- 1007651838  DIAZ RODRIGUEZ RONALD SNEIDER
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 152;  -- 1007651973  RIOS HERRERA YENIFER LEANDRA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 153;  -- 1007694183  BAÑOL TAPASCO YEISON ESTIVEN
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 154;  -- 1007808097  CHALARCA GARCIA KEVIN GIOVANY
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 155;  -- 1007808107  LENGUA CALVO CARLOS FERNANDO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 1;  -- 1007808313  HERNANDEZ LARGO JUAN FELIPE
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 2;  -- 1017222157  LONDONO VALLE SEBASTIAN
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 168;  -- 1020816676  CARDONA BETANCOURT SARA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 169;  -- 1025763301  OCHOA MARULANDA DEIMER
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 5;  -- 1033340485  ARISMENDY AGUDELO ALEJANDRA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 6;  -- 1034776899  LADINO GONZALEZ CAMILO ANDRES
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 7;  -- 1034986488  CALLE PALMETT JUAN ESTEBAN
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 8;  -- 1035871844  MEJIA OSORIO MANUELA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 170;  -- 1036961944  MARIN QUINTERO MARIA FERNANDA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 10;  -- 1037449092  MAZO OLARTE LEIDY SULAY
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 12;  -- 1037614187  AMAYA LOPEZ CAROLINA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 14;  -- 1039023530  BETANCOURT TAMAYO NESTOR IVAN
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 15;  -- 1039198133  RAMIREZ OBANDO STIVEN
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 16;  -- 1039462457  RAMIREZ ORTIZ DANIELA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 17;  -- 1045046238  OSPINA ECHEVERRY ANGELA YULIETH
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 20;  -- 1053765412  LEON MARULANDA SERGIO ANDRES
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 22;  -- 1053823924  ARANGO TRUJILLO MARCELO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 23;  -- 1053838548  OCAMPO SALAZAR LAURA DAYANA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 24;  -- 1053842239  ARICAPA TREJOS VAIRON CAMILO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 25;  -- 1053855982  CORDOBA SANCHEZ LAURA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 26;  -- 1053856093  NARANJO CARDENAS PAULA MARIA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 27;  -- 1053857485  OROZCO RIOS JONATHAN
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 28;  -- 1053868509  PARRA MOSQUERA JUAN DIEGO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 29;  -- 1053871088  ALVAREZ HURTADO ANGELA MARCELA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 30;  -- 1053871279  LOPEZ GIRALDO MARIANA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 31;  -- 1053872960  RESTREPO RENDON LUISA MARIA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 32;  -- 1054990613  SANTANA PEREZ JULIANA ANDREA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 33;  -- 1054997974  GIL JIMENEZ ANYI DAHIANA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 34;  -- 1058228119  IZQUIERDO DIAZ MARLON ARTURO
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 35;  -- 1058228240  VELASQUEZ IZQUIERDO LAURA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 36;  -- 1058229120  MORENO CASTRILLON YANETH ORLANDY
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 37;  -- 1058230681  CASTRO ESCOBAR YESMITH VERONICA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 38;  -- 1059694220  MONTOYA SOTO MAYERLY ANDREA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 39;  -- 1059694771  TREJOS DIAZ ANDREA
    UPDATE GN_FUNCI SET COD_ESTCIV = 1, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 40;  -- 1059706306  MAFLA SOTO CONNY DAYANA

    -- ┌─ CASADO/A (COD_ESTCIV = 2) · 28 registros ─────────
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 107;  -- 6615269  OROPEZA MENDOZA VICTOR MANUEL
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 159;  -- 11004336  BUSTOS RUBIO RAFAEL ENRIQUE
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 85;  -- 13511547  OSSMA GOMEZ OMAR DAVID
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 86;  -- 15447956  HERRERA OSORIO JHON ALBERTO
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 87;  -- 15923454  LADINO ALVAREZ JHON JAIRO
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 92;  -- 16053295  MONTES RINCON JOSE ROGELIO
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 102;  -- 37547926  OSPINA SERRANO MARIA JULIANA
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 111;  -- 74382199  HIGUERA GARZON RODOLFO
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 112;  -- 75065818  VALLEJO LONDOÑO ROBINSON
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 113;  -- 75067991  VALLEJO VALLEJO CARLOS ELIAS
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 114;  -- 75079022  CRUZ SANCHEZ MAURICIO JAVIER
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 116;  -- 75102710  SUAREZ GOMEZ ALEJANDRO
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 122;  -- 79748522  PEÑUELA GOMEZ JAIME HUMBERTO
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 162;  -- 79779721  ARDILA CASTRO JOSE MARIA
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 124;  -- 80014013  ESPITIA MONTOYA IVAN DARIO
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 127;  -- 80203035  SABRICA BUENDIA CARLOS ANDRES
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 131;  -- 93341202  HIDALGO CASTILLO YESID
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 51;  -- 1060592188  GAÑAN TAPASCO VICTOR JULIO
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 52;  -- 1060592562  ARREDONDO ANZOLA DANIEL ALAIN
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 74;  -- 1101440352  BANQUEZ MATURANA MIGUEL
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 77;  -- 1128391597  ALVAREZ GALEANO JUAN DAVID
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 78;  -- 1128415118  MONTOYA MONTOYA PABLO ESTEBAN
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 3;  -- 10276733  GRANADA VALENCIA JAIME
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 9;  -- 1036625005  RICO GODOY CATHERINE
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 13;  -- 1037624001  ORTIZ LOPEZ WILMAR ALEXIS
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 18;  -- 1053764443  LOMBANA GOMEZ VALENTINA
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 19;  -- 1053765183  VARGAS GONZALEZ NATALIA
    UPDATE GN_FUNCI SET COD_ESTCIV = 2, ACT_USUA = 'MineDax ', ACT_HORA = GETDATE() WHERE COD_FUNCI = 21;  -- 1053784995  RAMIREZ MOSQUERA HENRY ALEXANDER

    -- ── CONFIRMACIÓN ──────────────────────────────────────────────────────
    COMMIT TRANSACTION;
    PRINT '✓ COMMIT completado — ' + CAST(152 AS VARCHAR) + ' registros actualizados.';

END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    PRINT '✗ ERROR — se ejecutó ROLLBACK.';
    PRINT 'Mensaje: ' + ERROR_MESSAGE();
    PRINT 'Línea:   ' + CAST(ERROR_LINE() AS VARCHAR);
END CATCH;
GO

-- ── VERIFICACIÓN POSTERIOR ─────────────────────────────────────────────────
-- Ejecuta esto después para confirmar los resultados:
SELECT
    ISNULL(ec.NOM_ESTCIV, '** NULL **') AS ESTADO_CIVIL,
    f.COD_ESTCIV,
    COUNT(*) AS TOTAL
FROM GN_FUNCI f
LEFT JOIN MAE_ESTCIV ec ON ec.COD_ESTCIV = f.COD_ESTCIV
GROUP BY f.COD_ESTCIV, ec.NOM_ESTCIV
ORDER BY f.COD_ESTCIV;